---
version: "3"
services:
    osrm-backend:
        tty: true
        stdin_open: true
        ports:
            - 5000:5000
        volumes:
            - ./data:/data
        image: osrm/osrm-backend
        command: osrm-routed --algorithm ch /data/germany-latest.osrm
    osrm-frontend:
        ports:
            - 9966:9966
        image: osrm/osrm-frontend
    open-elevation:
        tty: true
        stdin_open: true
        volumes:
            - ./elevation/data:/code/data
        ports:
            - 9967:8080
        image: openelevation/open-elevation
    app:
        image: 'docker.io/jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
           - '80:80'
           - '81:81'
           - '443:443'
        volumes:
           - ./data:/data
           - ./letsencrypt:/etc/letsencrypt
